spring.application.name=habitos

# ==========================================
# CONFIGURACION DE CONEXION A YUGABYTEDB
# ==========================================
# Probaremos usando el puerto 5433 optimizado pero desactivando la validacion estricta de archivo temporalmente
spring.datasource.url=jdbc:postgresql://us-east-1.e6045396-c5c5-44a8-bfae-da1c63ced758.aws.yugabyte.cloud:5433/yugabyte?ssl=true&sslmode=require
spring.datasource.username=heda0706
spring.datasource.password=Amoadavid123
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACION DE JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CONFIGURACION DE SWAGGER / OPENAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# CONFIGURACION DE CORREO ELECTRONICO (GMAIL)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Ingresa aqui tu correo de Gmail real
spring.mail.username=deiiviid622@gmail.com

# Ingresa aqui la contrasena de 16 caracteres que generaste (sin espacios)
spring.mail.password=ttybzmndfvnrhhg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2