spring.application.name=habitos

# ==========================================
# CONFIGURACIN DE CONEXIN A YUGABYTEDB
# ==========================================
# Probaremos usando el puerto 5433 optimizado pero desactivando la validacin estricta de archivo temporalmente
spring.datasource.url=jdbc:postgresql://us-east-1.e6045396-c5c5-44a8-bfae-da1c63ced758.aws.yugabyte.cloud:5433/yugabyte?ssl=true&sslmode=require
spring.datasource.username=heda0706
spring.datasource.password=Amoadavid123
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACIN DE JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CONFIGURACIN DE SWAGGER / OPENAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# CONFIGURACIN DE CORREO ELECTRNICO (MAILTRAP SMTP)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=d34307e1135caa
spring.mail.password=b5d243f0745b0e
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true